name:                un-unicode
version:             0.1.0.0
github:              "czhang03/un-unicode"
license:             GPL-3
author:              "C. Zhang"
maintainer:          "czhang03_gh@tutanota.com"
copyright:           "2024 C. Zhang"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Convert unicode math symbols in a text to LaTeX commands.

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  un-unicode-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - un-unicode

tests:
  un-unicode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - un-unicode
